app/models.py
#!/usr/bin/env python
from flask_login import UserMixin, AnonymousUserMixin
from . import db, login_manager
from flask import current_app
from werkzeug.security import generate_password_hash, check_password_hash


# from flask import current_app

class Permission:
    FOLLOW = 1  # 关注其他用户
    COMMENT = 2  # 在他人撰写的文章中发布评论
    WRITE = 4  # 写原创文章
    MODERATE = 8  # 查处他人发表的不当评论
    ADMIN = 16  # 管理网站


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True, index=True)
    default = db.Column(db.Boolean, default=False, index=True)
    permissions = db.Column(db.Integer)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __init__(self, **kwargs):
        super(Role, self).__init__(**kwargs)
        if self.permissions is None:
            self.permissions = 0

    @staticmethod
    def insert_roles():
        roles = {
            'User': [Permission.FOLLOW, Permission.COMMENT, Permission.WRITE],
            'Moderator': [Permission.FOLLOW, Permission.COMMENT,
                          Permission.WRITE, Permission.MODERATE],
            'Administrator': [Permission.FOLLOW, Permission.COMMENT,
                              Permission.WRITE, Permission.MODERATE,
                              Permission.ADMIN],
        }
        default_role = 'User'
        for r in roles:
            role = Role.query.filter_by(name=r).first()
            if role is None:
                role = Role(name=r)
            role.reset_permissions()
            for perm in roles[r]:
                role.add_permission(perm)
            role.default = (role.name == default_role)
            db.session.add(role)
        db.session.commit()

    def add_permission(self, perm):
        if not self.has_permission(perm):
            self.permissions += perm

    def remove_permission(self, perm):
        if self.has_permission(perm):
            self.permissions -= perm

    def reset_permissions(self):
        self.permissions = 0

    def has_permission(self, perm):
        return self.permissions & perm == perm

    def __repr__(self):
        return '<Role %r>' % self.name


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    password_hash = db.Column(db.String(128))
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    email = db.Column(db.String(64), unique=True, index=True)

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['FLASKY_ADMIN']:
                self.role = Role.query.filter_by(name='Administrator').first()
            if self.role is None:
                self.role = Role.query.filter_by(default=True).first()

    def can(self, perm):
        return self.role is not None and self.role.has_permisson(perm)

    def is_administrator(self):
        return self.can(Permission.ADMIN)

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute!')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User %r>' % self.username


class AnonymousUser(AnonymousUserMixin):
    def can(self, permissions):
        return False

    def is_administrator(self):
        return False


login_manager.anonymous_user = AnonymousUser


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
#!/usr/bin/env python
from flask_wtf import FlaskForm
from wtforms import *

class NameForm(FlaskForm):
    name = StringField('what is your name?', validators=[validators.DataRequired()])
    texts = TextAreaField()
    submit = SubmitField('Submit')

app/__init__.py
#!/usr/bin/env python

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
login_manager = LoginManager()

login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    # 初始化app
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # 注册蓝本
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
#!/usr/bin/env python
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors
from ..models import Permission

@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/main/views.py
#!/usr/bin/env python
from datetime import datetime
from flask import render_template, session, redirect, url_for, flash, current_app

from . import main
from .forms import NameForm
from .. import db
from ..models import Role, User
from ..email import send_email


@main.route('/', methods=['GET', 'POST'])
def index():
    # user_agent=request.headers.get('user-agent')
    return render_template('index.html', current_time=datetime.utcnow())


@main.route('/user/', methods=['GET', 'POST'])
@main.route('/user/<name>', methods=['GET', 'POST'])
def user(name=None):
    form = NameForm()
    lt = []
    session['name'] = name
    for i in range(5):
        lt.append(i)
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.name.data).first()
        old_name = session.get('name')
        if old_name is not None and old_name != form.name.data:
            flash('Look like you have changed your name!')
            if user is None:
                # user_role = Role(name='Admin')
                user = User(username=form.name.data, role_id=3)
                db.session.add(user)
                db.session.commit()
                session['known'] = False
                if current_app.config['FLASKY_ADMIN']:
                    send_email(current_app.config['FLASKY_ADMIN'], 'New User', 'mail/new_user', user=user)
            else:
                session['known'] = True
        session['name'] = form.name.data
        session['retext'] = form.texts.data
        return redirect(url_for('main.user', name=session.get('name')))
    return render_template('user.html', form=form, name=session.get('name'), comments=lt, retext=session.get('retext'),
        known=session.get('known', False))


@main.route('/data_visual/', methods=['GET'])
def data_visual():
    return render_template('data_visual.html')

app/templates/base.html
{% extends "bootstrap/base.html" %} <!-- base.html模板继承自bootstrap/base.html -->
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flask{% endblock %}

{% block head %}
    {{ super() }}
    {% block styles %}
        {{ super() }}
        <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/darkly/bootstrap.min.css">
    {% endblock %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static',filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-taget=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Flasky</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    <li><a href="{{ url_for('main.user') }}">User</a></li>
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    <li><a href="{{ url_for('main.data_visual') }}">DataVisual</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    {% else %}
                        <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}

        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

app/templates/base1.html
{% extends "bootstrap/base.html" %} <!-- base.html模板继承自bootstrap/base.html -->
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flask{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static',filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

{% include "common/header.html" %}<!--引入网页的头部模板-->
{% block navbar %}
    <div class="container">
        <div class="row row-offcanvas row-offcanvas-right">
            {% block content %}<!--自定义模板区域-->

            {% endblock %}
            {% include "common/sidebar.html" %}<!--引入网页的侧边模板-->
        </div><!--/row-->
        {#            {% include "common/footer.html" %}<!--引入网页的底部模板-->#}
    </div>
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/darkly/bootstrap.min.css">
{% endblock %}

{#{% block content %}#}
{#    <div class="container">#}
{#        {% block page_content %}{% endblock %}#}
{#    </div>#}
{#{% endblock %}#}

app/templates/baseB.html
{% extends "bootstrap/base.html" %} <!-- base.html模板继承自bootstrap/base.html -->
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flask{% endblock %}

{% block head %}
    {{ super() }}
    {% block styles %}
        {{ super() }}
        <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/darkly/bootstrap.min.css">
    {% endblock %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static',filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-taget=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Flasky</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    <li><a href="{{ url_for('main.user') }}">User</a></li>
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    <li><a href="{{ url_for('main.data_visual') }}">DataVisual</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    {% else %}
                        <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}

        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

app/templates/common/header.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-taget=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Flasky</a>
{#            <a class="navbar-brand" href="{{ url_for('main.user') }}">User</a>#}
{#            <a class="navbar-brand" href="{{ url_for('auth.login') }}">Login</a>#}
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{{ url_for('main.index') }}">Home</a>
                </li>
                <li>
                    <a href="{{ url_for('main.user') }}">User</a>
                </li>
                <li>
                    <a href="{{ url_for('auth.login') }}">Login</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

app/templates/common/sidebar.html
<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
    <div class="list-group">
        <a href="#" class="list-group-item active">
            <button type="button" class="btn btn-block btn-danger" aria-label="Left Align">
                <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
            </button>
        </a>
        <a href="#" class="list-group-item">
            <button type="button" class="btn btn-block btn-info" aria-label="Left Align">
                <span class="glyphicon glyphicon-align-center" aria-hidden="true"></span>
            </button>
        </a>
        <a href="#" class="list-group-item">
            <button type="button" class="btn btn-primary" aria-label="Left Align">
                <span class="glyphicon glyphicon-align-right" aria-hidden="true"></span>
            </button>
        </a>
        <a href="#" class="list-group-item">
            <button type="button" class="btn btn-success" aria-label="Left Align">
                <span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span>
            </button>
        </a>
        <a href="#" class="list-group-item">
            <button type="button" class="btn btn-block btn-warning" aria-label="Left Align">
                <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
            </button>
        </a>
        <a href="{{ url_for('main.index') }}" class="list-group-item">Home</a>
        <a href="{{ url_for('main.user') }}" class="list-group-item">User</a>
        <a href="{{ url_for('auth.login') }}" class="list-group-item">Login</a>
    </div>
</div><!--/.sidebar-offcanvas-->

app/templates/data_visual.html
{% extends "baseB.html" %}

{% block title %}Data visual{% endblock %}

{% block head %}
    {{ super() }}
    <script src={{ url_for('static',filename='js/config.js') }}></script>
    <script src={{ url_for('static',filename='js/visual.js') }}></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        window.onload = load();
    </script>
{% endblock %}

{% block page_content %}
    <center>
        <!--<input type="file" id="inputfile" name="fileContent">-->
        <svg width="1440" height="880"></svg>
        <link href="{{ url_for('static', filename='css/stylesheet.css') }}" rel="stylesheet">
    </center>
{% endblock %}

app/templates/data_visual2.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <script src={{ url_for('static',filename='js/config.js') }}></script>
    <script src={{ url_for('static',filename='js/visual.js') }}></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <title>动态排名数据可视化 ver1.3 By Jannchie</title>
</head>
<body onload="load()">
{#<a href="{{ url_for('main.index') }}">Home</a>#}
<center>
    <!--<input type="file" id="inputfile" name="fileContent">-->
    <svg width="1440" height="900" y="20"></svg>
    <link href="{{ url_for('static', filename='css/stylesheet.css') }}" rel="stylesheet">
</center>
</body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block page_content %}
    {% if current_user.is_authenticated %}
        <h1>Hello,{{ current_user.username }}.</h1>
    {% else %}
        <h1>Hello,World!</h1>
    {% endif %}
    <div>
        {{ moment(current_time).format('LLL') }}.
        refresh at {{ moment(current_time).fromNow(refresh=True) }}
    </div>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block title %}User{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block page_content %}
    {#            {% for message in get_flashed_messages() %}#}
    {#                <div class="alert alert-warning">#}
    {#                    <button type="button" class="close" data-dismiss="alert">&times;</button>#}
    {#                    {{ message }}#}
    {#                </div>#}
    {#            {% endfor %}#}
    <div class="page-header">
        {% if name %}
            <h1>Hello,{{ name }}!</h1>
        {% else %}
            <h1>Hello,strang!</h1>
        {% endif %}
        <div>
            <ul>
                {% for comment in comments %}
                    <li>{{ comment }}</li>
                {% endfor %}
            </ul>
        </div>
        {{ wtf.quick_form(form) }}
        <div style="margin-top: 10px">
            <textarea title="retext" class="form-control" placeholder="From Texts">{{ retext }}</textarea>
        </div>
    </div>
{% endblock %}